### ISSUE TITLE
no_pca.keras

### ISSUE THREAD

**Issue by juanluisrosaramos** [ju-leon/RetouchML#2]
Hi!!
Is it possible to recover your trained classifier? Nowadays it's in your gdrive bin.
I found one file named like that ut it's not working keras_engine is saying " 275     model_weights_group = h5dict['model_weights']
AttributeError: 'str' object has no attribute 'decode'"
The file is only 827,1 KiB so not sure if it's your trained classifier.
Thanks!!

**Comment by ju-leon** [comment]
Hi, 
the file should be available under the following link again:
https://drive.google.com/file/d/1--6jvVYGf1SCm4s72CBCSvYcJ6zoob0B/view

I've also attached it to this issue in case I accidentally move it to trash in Google Drive again:
[no_pca.keras.zip](https://github.com/ju-leon/RetouchML/files/8161823/no_pca.keras.zip)

**Comment by DaichiFujiwara** [comment]
Hello, I have a problem for no_pca.keras file.

I loaded this model and just wanted to do 'model.predict(latent_vector)".
But I always got an error, which says "Could not find variable dense_3/kernel". 
Do you have an idea to resolve this problem?

Just to be sure, I show the hierarchical structure of loaded model.

Thanks advance.

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_1 (Dense)              multiple                  65664     
_________________________________________________________________
dense_2 (Dense)              multiple                  2064      
_________________________________________________________________
dense_3 (Dense)              multiple                  136       
_________________________________________________________________
dense_4 (Dense)              multiple                  9
=================================================================
Total params: 67,873
Trainable params: 67,873
Non-trainable params: 0
_________________________________________________________________
